# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f60e1227b1e44f266ac6d4d890052e0251797cf8ea3d58cc4a223561c2c6186f36cdd466d5810ba66ef49b0cb8c7dea8e00a74be97d615d70c406aeea15fe29d

test:
  secret_key_base: 93e1ef4a38beacce9989fc8514838af4ce72a3ad6b6f5a4582b8b8539955b48a2cb6e22a5cf85855f44c0e485dcaf5507ed2db5a8ad9ef77be2a57bfe495dd7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
